DEFAULT_NOTIFICATION_PAGE_SIZE = 10

"""
"General" notifications include:
	1. FriendRequest
	2. FriendList
"""
GENERAL_MSG_TYPE_NOTIFICATIONS_PAYLOAD = 0  
GENERAL_MSG_TYPE_PAGINATION_EXHAUSTED = 1 
GENERAL_MSG_TYPE_NOTIFICATIONS_REFRESH_PAYLOAD = 2 
GENERAL_MSG_TYPE_GET_NEW_GENERAL_NOTIFICATIONS = 3 
GENERAL_MSG_TYPE_GET_UNREAD_NOTIFICATIONS_COUNT = 4  
GENERAL_MSG_TYPE_UPDATED_NOTIFICATION = 5  


"""
"Chat" notifications include:
	1. UnreadChatRoomMessages
"""
CHAT_MSG_TYPE_NOTIFICATIONS_PAYLOAD = 10  
CHAT_MSG_TYPE_PAGINATION_EXHAUSTED = 11  
CHAT_MSG_TYPE_GET_NEW_NOTIFICATIONS = 13 
CHAT_MSG_TYPE_GET_UNREAD_NOTIFICATIONS_COUNT = 14 
